# -*- coding: utf-8 -*-
"""visualizationTechniques.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dM3ONAcYwMSpv9nTOEOUsU1AcLd9fXOT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

trees = pd.read_csv("trees.csv")

trees.shape

trees.head()

# Histogramas

# Girth Column
plt.hist(trees.iloc[:,0], bins=6)
plt.title("Trees")
plt.ylabel("Frequency")
plt.xlabel("Girth")

# Height Column
plt.hist(trees.iloc[:,1], bins=6)
plt.title("Trees")
plt.ylabel("Frequency")
plt.xlabel("Height")

# Volume Column
plt.hist(trees.iloc[:,2], bins=6)
plt.title("Trees")
plt.ylabel("Frequency")
plt.xlabel("Height")

# Histogram with sns
sns.histplot(trees.iloc[:,1], kde=False, bins=6, color="Purple").set(title="Trees")

# Dispersion line
sns.kdeplot(trees.iloc[:,1],color="Purple").set(title="Trees")

# Histogram and dispersion line
sns.histplot(trees.iloc[:,1], kde=True, bins=6, color="Purple").set(title="Trees")